### PR TITLE
Fix overlapping Gravatar when leaving a comment

### LINKED ISSUE #213: Placement of comment user avatar/gravatar is off
This only happens on posts/pages that don't have comments yet. The comment user avatar's placement is off and covers the top part of the comment form. Happens on both logged out and logged in users.

comment-logged-out
comment-logged-in

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #213

<table>
<tr>
<td>Before:

213 - before</td>
<td>After:

213 - after</td>
</tr>
</table>

### CODE REVIEW

File: inc/template-functions.php [hunk 1]
```diff
@@ -113,6 +113,15 @@ function twentynineteen_can_show_post_thumbnail() {
 	return ! post_password_required() && ! is_attachment() && has_post_thumbnail();
 }
 
+/**
```
Comment (kjellr) [inline inc/template-functions.php]: @nielslange This doesn't seem like it should be included in this PR. Can you remove this function to sync back up with master?

Comment (nielslange) [reply inc/template-functions.php]: @kjellr Good catch! This code seemed to slip in there accidentally. I just removed it and updated this PR.
